# Generated by Django 3.2 on 2022-06-19 08:08

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='DC名称')),
                ('location', models.CharField(max_length=100, verbose_name='位置')),
            ],
            options={
                'verbose_name': 'DC信息',
                'verbose_name_plural': 'DC信息',
                'db_table': 'df_dc_info',
            },
        ),
        migrations.CreateModel(
            name='DCRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20, verbose_name='机柜编号')),
                ('power_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='可用功率')),
                ('power_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已用功率')),
                ('unite', models.CharField(max_length=20, verbose_name='功率单位')),
            ],
            options={
                'verbose_name': '机柜信息',
                'verbose_name_plural': '机柜信息',
                'db_table': 'df_rack_info',
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='设备SPU名称')),
                ('detail', tinymce.models.HTMLField(blank=True, verbose_name='设备详情')),
            ],
            options={
                'verbose_name': '设备SPU',
                'verbose_name_plural': '设备SPU',
                'db_table': 'df_devices',
            },
        ),
        migrations.CreateModel(
            name='DevicesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='种类名称')),
                ('logo', models.CharField(max_length=20, verbose_name='标识')),
                ('image', models.ImageField(upload_to='type', verbose_name='设备类型图片')),
            ],
            options={
                'verbose_name': '设备种类',
                'verbose_name_plural': '设备种类',
                'db_table': 'df_goods_type',
            },
        ),
        migrations.CreateModel(
            name='DevicesSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='设备名称')),
                ('desc', models.CharField(max_length=256, verbose_name='设备简介')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='设备价格')),
                ('unite', models.CharField(max_length=20, verbose_name='设备单位')),
                ('image', models.ImageField(upload_to='goods', verbose_name='设备图片')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.devices', verbose_name='设备SPU')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.devicestype', verbose_name='设备种类')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'df_goods_sku',
            },
        ),
    ]
