# Generated by Django 3.2 on 2022-06-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devicessku',
            table='df_devices_sku',
        ),
        migrations.AlterModelTable(
            name='devicestype',
            table='df_devices_type',
        ),
    ]
