# Generated by Django 3.2 on 2022-12-28 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0002_auto_20220619_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicessku',
            name='image',
        ),
        migrations.AddField(
            model_name='dcrack',
            name='dc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcinfo', verbose_name='所属机房'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='dc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcinfo', verbose_name='所属机房'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='image_behind',
            field=models.ImageField(default=1, upload_to='goods', verbose_name='设备反面图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='image_front',
            field=models.ImageField(default=1, upload_to='goods', verbose_name='设备正面图片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='slot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcrack', verbose_name='槽位'),
            preserve_default=False,
        ),
    ]
