# Generated by Django 3.2 on 2022-12-28 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0003_auto_20221228_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicessku',
            name='slot_id',
        ),
        migrations.AddField(
            model_name='devicessku',
            name='dc_rack_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcrack', verbose_name='所属机柜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='slot',
            field=models.CharField(default=1, max_length=20, verbose_name='槽位'),
            preserve_default=False,
        ),
    ]
