# Generated by Django 3.2 on 2022-12-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_remove_devicessku_dc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dcrack',
            old_name='no',
            new_name='name',
        ),
    ]
