# Generated by Django 3.2 on 2022-12-30 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0006_rename_no_dcrack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcrack',
            name='name',
            field=models.CharField(max_length=20, verbose_name='机柜名称'),
        ),
        migrations.CreateModel(
            name='DCRackInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='槽位编号')),
                ('used', models.BooleanField(verbose_name='是否空闲')),
                ('device_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.devicessku', verbose_name='所属设备')),
            ],
        ),
    ]
