# Generated by Django 3.2 on 2022-12-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0007_auto_20221230_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicessku',
            old_name='unite',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='devicessku',
            name='dc_rack_id',
        ),
        migrations.RemoveField(
            model_name='devicessku',
            name='slot',
        ),
        migrations.AddField(
            model_name='dcrackinfo',
            name='dc_rack_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcrack', verbose_name='所属机柜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicessku',
            name='size',
            field=models.CharField(default=1, max_length=20, verbose_name='设备U数'),
            preserve_default=False,
        ),
    ]
