# Generated by Django 3.2 on 2022-12-30 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0008_auto_20221230_0629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcrackinfo',
            options={'verbose_name': '机柜详情', 'verbose_name_plural': '机柜详情'},
        ),
        migrations.AlterModelTable(
            name='dcrackinfo',
            table='df_rack_info_details',
        ),
    ]
