# Generated by Django 3.2 on 2023-01-03 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0009_auto_20221230_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcrackinfo',
            name='dc_rack_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcrack', verbose_name='所属机柜'),
        ),
        migrations.AlterField(
            model_name='dcrackinfo',
            name='device_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.devicessku', verbose_name='所属设备'),
        ),
    ]
