# Generated by Django 3.2 on 2023-01-05 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0015_auto_20230104_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devices',
            new_name='DevicesSPU',
        ),
        migrations.RenameField(
            model_name='dcrack',
            old_name='dc_id',
            new_name='dc',
        ),
        migrations.RenameField(
            model_name='dcrackinfo',
            old_name='dc_rack_id',
            new_name='dc_rack',
        ),
    ]
