# Generated by Django 3.2 on 2023-01-05 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0016_auto_20230105_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcrackinfo',
            name='dc_rack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dcim.dcrack', verbose_name='所属机柜'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dcrackinfo',
            unique_together={('name', 'dc_rack')},
        ),
    ]
