# Generated by Django 3.2 on 2023-01-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0017_auto_20230105_0209'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dcrackinfo',
            unique_together=set(),
        ),
    ]
