# Generated by Django 3.2 on 2023-01-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0018_alter_dcrackinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dcrackinfo',
            unique_together={('name', 'dc_rack')},
        ),
    ]
