# Generated by Django 3.2 on 2023-01-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0020_auto_20230105_0302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dcinfo',
            table=None,
        ),
    ]
