# Generated by Django 3.2 on 2023-01-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0021_alter_dcinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicessku',
            name='slot_begin',
            field=models.IntegerField(default=1, verbose_name='设备位置'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicessku',
            name='size',
            field=models.IntegerField(verbose_name='设备U数'),
        ),
    ]
